In [2]:
import numpy as np
import pandas as pd

from gretel_synthetics.timeseries_dgan.dgan import DGAN
from gretel_synthetics.timeseries_dgan.config import DGANConfig, OutputType, Normalization

In [ ]:
df = pd.read_csv('../data/csv/plant_data.csv')

In [7]:
import pandas as pd
import numpy as np

np.random.seed(42)  # Set a seed for reproducibility

hours = 3 * 7 * 24  # 3 weeks of data with hourly intervals
dates = pd.date_range('20220101', periods=hours, freq='H')  # Create a datetime index

# Generate synthetic data using random numbers
temperature_c = np.random.normal(20, 1, hours)
humidity = np.random.normal(50, 3, hours)

# Generate soil moisture data based on humidity
moisture_multiplier = 50
soil_moisture = 20000 + (humidity - humidity.min()) * moisture_multiplier
trend_factor = np.linspace(-5000, 5000, hours)
soil_moisture = np.clip(soil_moisture + trend_factor, 20000, 22000)

# Depend light intensity on temperature and humidity
temperature_threshold = 22
humidity_threshold = 40
light_intensity = np.where((temperature_c > temperature_threshold) & (humidity < humidity_threshold), 1, 0)

temperature_f = temperature_c * 9/5 + 32

# Create a pandas DataFrame
data = pd.DataFrame({
    'date_time': dates,
    'temperature_c': temperature_c,
    "temperature_f": temperature_f,
    'humidity': humidity,
    'soil_moisture (%)': soil_moisture,
    'light': light_intensity
}) # Display the first 5 rows
# data.to_csv('synthetic_plant_sensor_data.csv', index=False)  # Save the data to a CSV file

In [8]:
data

,date_time,temperature_c,temperature_f,humidity,soil_moisture (%),light
0,2022-01-01 00:00:00,20.496714,68.894085,48.048072,20000.0,0
1,2022-01-01 01:00:00,19.861736,67.751124,48.538624,20000.0,0
2,2022-01-01 02:00:00,20.647689,69.165839,48.222818,20000.0,0
3,2022-01-01 03:00:00,21.523030,70.741454,47.408028,20000.0,0
4,2022-01-01 04:00:00,19.765847,67.578524,50.145565,20000.0,0
...,...,...,...,...,...,...
499,2022-01-21 19:00:00,18.617200,65.510960,48.059190,22000.0,0
500,2022-01-21 20:00:00,20.926178,69.667120,52.094670,22000.0,0
501,2022-01-21 21:00:00,21.909417,71.436950,51.180456,22000.0,0
502,2022-01-21 22:00:00,18.601432,65.482578,52.685580,22000.0,0
503,2022-01-21 23:00:00,20.562969,69.013345,51.905515,22000.0,0

In [13]:
data.to_csv('../data/csv/plant_syn.csv', index=False)